query getUser {
  user(self: true) {
    _id
    username
    library {
      collections {
        _db
        _collection
        _id
        name
        icon
        description
        path
        slug

        typeFormats {
          graphql
        }

        fields {
          name
          type
          required
          isArray
          renderMethod
        }

        defaultView {
          type
        }
      }
    }
  }
}
