query getUser {
  user: me {
    _id
    username
    library {
      collections {
        _db _collection _id
        name icon path
        description
        fields { name type required isArray }
        defaultView { type }
        creator { username }
      }
    }
  }
}
